name: Issue Comment Commands

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  handle-start-command:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '/start')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4
        with:
          repository: idynic/idynic-github-actions
          path: .github/actions
          token: ${{ secrets.PROJECT_TOKEN }}

      - name: Add debug output
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Comment User: ${{ github.event.comment.user.login }}"
          echo "GitHub token available: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "Project token available: ${{ secrets.PROJECT_TOKEN != '' }}"
          echo "Current directory:"
          ls -la
          echo "GitHub Actions directory:"
          ls -la .github/actions

      - name: Handle start command
        id: handle-start-command
        uses: ./.github/actions/handle-issue-commands
        with:
          command: 'start'
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          comment-user: ${{ github.event.comment.user.login }}

      - name: Create branch for issue
        if: steps.handle-start-command.outputs.authorized == 'true' && steps.handle-start-command.outputs.processed == 'true'
        uses: ./.github/actions/create-issue-branch
        with:
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      # Direct implementation of status update
      - name: Update issue status to In Progress
        if: steps.handle-start-command.outputs.authorized == 'true' && steps.handle-start-command.outputs.processed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `✅ Issue status updated to: **In Progress**\n\nA branch has been created for you to work on this issue.`
            });
            
            console.log(`Updated status of issue #${{ github.event.issue.number }} to In Progress`);