name: 'Extract Issue Reference'
description: 'Extract issue number from branch name following standard format issue-XXX'
inputs:
  branch-name:
    description: 'The branch name to extract issue number from'
    required: true

outputs:
  issue-number:
    description: 'The extracted issue number (if found)'
    value: ${{ steps.extract.outputs.issue_number }}
  found:
    description: 'Whether an issue number was found'
    value: ${{ steps.extract.outputs.found }}

runs:
  using: 'composite'
  steps:
    - name: Extract issue number from branch name
      id: extract
      shell: bash
      run: |
        BRANCH_NAME="${{ inputs.branch-name }}"
        echo "Extracting issue number from branch: $BRANCH_NAME"
        
        # Extract issue number from branch name (issue-123-description or issue-123)
        if [[ "$BRANCH_NAME" =~ ^issue-([0-9]+) ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[1]}"
          echo "Found issue number: #$ISSUE_NUMBER"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT
        else
          echo "No issue number found in branch name"
          echo "found=false" >> $GITHUB_OUTPUT
        fi